apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/alhennessey92/traders_guild_applications"
    targetRevision: HEAD
    path: fastapi/kubernetes  # Adjust this based on your repo structure
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true