apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: us-cental1-docker.pkg.dev/traders-guild-dev/traders-guild/fastapi:latest
        ports:
        - containerPort: 8000