name: Deploy FastAPI to GKE (Daily)

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight UTC daily
  workflow_dispatch:  # Allows manual trigger
  # push:
  #   branches:
  #     - main

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG="dev-$(date +%Y%m%d%H%M%S)"
          docker build -t us-central1-docker.pkg.dev/traders-guild-dev/traders-guild/fastapi:$IMAGE_TAG .
          docker push us-central1-docker.pkg.dev/traders-guild-dev/traders-guild/fastapi:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update Kubernetes Deployment Manifest
        run: |
          sed -i "s|image: .*|image: us-central1-docker.pkg.dev/traders-guild-dev/traders-guild/fastapi:${{ env.IMAGE_TAG }}|" k8s/deployment.yaml
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add kubernetes/deployment.yaml
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
          git push